<?php
echo '{
	"showName":                             "CSI: TASMANIA - TAF2021 LIVE and DIGITAL Festival",
	"showId":                               "lGDFR72xan",
	"showBG":                               "/events/images/backgrounds/4.jpg",
	"createdByUserId":                      "1",
	"createdByUserCompany":                 "Scene Change Tasmania",
    "requireLogin":                         "true",
	"dateAdded":                            "1604598831",
	"showSubTitle":                         "An SOC Talk-Fest",
	"showDescription":                      "Show 3 Description",
	"showBackgroundImage":                  "PI8DCxkSus.jpg",
	"navBarColor":                          "rgba(255, 255, 255, 1)",
	"navBarBGColor":                        "rgba(96, 140, 96, 1)",
    "ChatBoxBGColor":                       "rgba(255, 255, 255, .8)",
    "ChatBoxTextColor":                     "rgba(129, 129, 129,1)",
    "ChatBoxIcon":                          "/events/images/icons/chatBox.png",
	"dataRows": [
        {   
            "ID":                           "EwE0NLOJNj",
            "displayOrder":                 "1",
            "displayDiv":                   "1",
            "rowType":                      "SponsorBanner",
            "SponsorBannerTextColor":       "rgba(129, 129, 129,1)",
            "SponsorBannerBGColor":         "rgba(255, 255, 255, .5)",
            "inScroller":                   "false"
        },
        {
            "ID":                           "jrxTRD0aOO",
            "displayOrder":                 "1",
            "displayDiv":                   "2",
            "rowType":                      "AgendaMenu",
            "AgendaMenuTextColor":          "rgba(129, 129, 129,1)",
            "AgendaMenuBGColor":            "rgba(255, 255, 255, .5)",
            "inScroller":                   "false",
            "tabs": [
                {
                    "label":                "MONDAY",
                    "ID":                   "ImyftecmJE"
                },
                {
                    "label":                "TUESDAY",
                    "ID":                   "z8JQAOnj7Q"
                }
            ]
        },
        
        {
            "ID":                           "E0NLOeP0G1",
            "displayOrder":                 "1",
            "displayDiv":                   "3",
            "rowType":                      "PlenarySession",
            "PlenarySessionHeader":         "BREAKFAST MEETING",
            "PlenarySessionIcon":           "/events/images/icons/breakfast.png",
            "PlenarySessionInfo":           "",
            "PlenarySessionStart":          "1633811431000",
            "PlenarySessionEnd":            "1633815031000",
            "PlenarySessionTextColor":      "rgba(129, 129, 129,1)",
            "PlenarySessionBGColor":        "rgba(255, 255, 255, .5)",
            "PlenarySessionButtonBGColor":  "rgba(96, 140, 96, 1)",
            "VideoURL":                     "https://vimeo.com/622025996",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {
            "ID":                           "GIJfAyS8bS",
            "displayOrder":                 "2",
            "displayDiv":                   "3",
            "rowType":                      "PlenarySession",
            "PlenarySessionHeader":         "PLENARY 1: Class aptent taciti sociosqu ad litora torquent",
            "PlenarySessionIcon":           "/events/images/icons/plenary.png",
            "PlenarySessionInfo":           "",
            "PlenarySessionStart":          "1633815031000",
            "PlenarySessionEnd":            "1633818631000",
            "PlenarySessionTextColor":      "rgba(129, 129, 129,1)",
            "PlenarySessionBGColor":        "rgba(255, 255, 255, .5)",
            "PlenarySessionButtonBGColor":  "rgba(96, 140, 96, 1)",
            "VideoURL":                     "https://vimeo.com/622025996",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
		{
			"ID":                           "tPrR1q6rAX",
            "displayOrder":                 "3",
            "displayDiv":                   "3",
            "rowType":                      "PlenarySession",
			"PlenarySessionHeader":         "PLENARY 2: At vero eos et accusamus et iusto odio dignissimos",
			"PlenarySessionIcon":           "/events/images/icons/plenary.png",
            "PlenarySessionInfo":           "",
            "PlenarySessionStart":          "1633819231000",
            "PlenarySessionEnd":            "1633822831000",
			"PlenarySessionTextColor":      "rgba(129, 129, 129,1)",
			"PlenarySessionBGColor":        "rgba(255, 255, 255, .5)",
			"PlenarySessionButtonBGColor":  "rgba(96, 140, 96, 1)",
            "VideoURL":                     "https://vimeo.com/473446147",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
		},
        {
            "ID":                           "L8II6qViNM",
            "displayOrder":                 "4", 
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentHeader",
            "ConcurrentHeaderText":         "CONCURRENT 1: At vero eos et accusamus et iusto odio dignissimos", 
            "ConcurrentHeaderIcon":         "/events/images/icons/concurrent.png", 
            "ConcurrentHeaderBGColor":      "rgba(255, 255, 255, .8)", 
            "ConcurrentHeaderTextColor":    "rgba(129, 129, 129,1)", 
            "ConcurrentHeaderInfo":         "Info",
            "ConcurrentHeaderStart":        "1633823431000",
            "ConcurrentHeaderEnd":          "1633827031000",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {
            "ID":                           "uuwjreP0G1",
            "displayOrder":                 "5",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession",
            "HeaderId" :                    "L8II6qViNM",
            "ConcurrentSessionText":        "STREAM 1: Iusto odio dignissimos",
            "ConcurrentSessionBGColor":     "rgba(90, 153, 82, 1)",
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)",
            "ConcurrentSessionButtonBG":    "rgba(96, 140, 96, 1)", 
            "ConcurrentSessionLastOne":     "false",
            "VideoURL":                     "https://vimeo.com/617054109",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {                               
            "ID":                           "lyUpyDCP9K",
            "displayOrder":                 "6",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession", 
            "HeaderId" :                    "L8II6qViNM",
            "ConcurrentSessionText":        "STREAM 2: Ad litora torquent", 
            "ConcurrentSessionBGColor":     "rgba(73, 155, 62, 1)", 
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)",  
            "ConcurrentSessionButtonBG":    "rgba(96, 140, 96, 1)", 
            "ConcurrentSessionLastOne":     "false",
            "VideoURL":                     "https://vimeo.com/618477950",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        { 
            "ID":                           "1DrHRkVt9h",
            "displayOrder":                 "7",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession", 
            "HeaderId" :                    "L8II6qViNM",
            "ConcurrentSessionText":        "STREAM 3: Et iusto odio dignissimos", 
            "ConcurrentSessionBGColor":     "rgba(67, 167, 54, 1)", 
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)", 
            "ConcurrentSessionButtonBG":    "rgba(96, 140, 96, 1)", 
            "ConcurrentSessionLastOne":     "false",
            "VideoURL":                     "https://vimeo.com/605584471",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        { 
            "ID":                           "y9p0w6QAg4",
            "displayOrder":                 "8",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession", 
            "HeaderId" :                    "L8II6qViNM",
            "ConcurrentSessionText":        "STREAM 4: Taciti sociosqu ad litora",  
            "ConcurrentSessionBGColor":     "rgba(43, 165, 27, 1)", 
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)",  
            "ConcurrentSessionButtonBG":    "rgba(96, 140, 96, 1)",  
            "ConcurrentSessionLastOne":     "true",
            "VideoURL":                     "https://vimeo.com/619427082",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {
            "ID":                           "L8II6eP0G1",
            "displayOrder":                 "9", 
            "displayDiv":                   "3",
            "rowType":                      "BreakTime",
            "BreakTimeText":                "LUNCH", 
            "BreakTimeIcon":                "/events/images/icons/lunch.png", 
            "BreakTimeBGColor":             "rgba(255, 255, 255, .8)", 
            "BreakTimeTextColor":           "rgba(129, 129, 129,1)", 
            "BreakTimeInfo":                "Info",
            "BreakTimeStart":               "1633827031000",
            "BreakTimeEnd":                 "1633827031000",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {
            "ID":                           "NfOFRnUz0O",
            "displayOrder":                 "10",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentHeader",
            "ConcurrentHeaderText":         "CONCURRENT 2: At vero eos et accusamus et iusto odio dignissimos",
            "ConcurrentHeaderIcon":         "/events/images/icons/concurrent.png",
            "ConcurrentHeaderBGColor":      "rgba(255, 255, 255, .8)",
            "ConcurrentHeaderTextColor":    "rgba(129, 129, 129,1)",
            "ConcurrentHeaderInfo":         "Info",
            "ConcurrentHeaderStart":        "1633830631000",
            "ConcurrentHeaderEnd":          "1633834231000",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        { 
            "ID":                           "wrdE8fltwQ", 
            "displayOrder":                 "11",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession",
            "HeaderId" :                    "NfOFRnUz0O",
            "ConcurrentSessionText":        "STREAM 1: Iusto odio dignissimos", 
            "ConcurrentSessionBGColor":     "rgba(0, 102, 251, 1)",
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)",
            "ConcurrentSessionButtonBG":    "rgba(0, 70, 176, 1)",   
            "ConcurrentSessionLastOne":     "false",
            "VideoURL":                     "https://vimeo.com/623563391",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {                               
            "ID":                           "H7frzbqJks",
            "displayOrder":                 "12", 
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession",
            "HeaderId" :                    "NfOFRnUz0O",
            "ConcurrentSessionText":        "STREAM 2: Ad litora torquent", 
            "ConcurrentSessionBGColor":     "rgba(49, 130, 252, 1)", 
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)", 
            "ConcurrentSessionButtonBG":    "rgba(0, 70, 176, 1)", 
            "ConcurrentSessionLastOne":     "false",
            "VideoURL":                     "https://vimeo.com/615614447",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {                               
            "ID":                           "OnAwQmqzkL",
            "displayOrder":                 "13",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession",
            "HeaderId" :                    "NfOFRnUz0O",
            "ConcurrentSessionText":        "STREAM 3: Et iusto odio dignissimos", 
            "ConcurrentSessionBGColor":     "rgba(108, 165, 251, 1)", 
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)", 
            "ConcurrentSessionButtonBG":    "rgba(0, 70, 176, 1)", 
            "ConcurrentSessionLastOne":     "false",
            "VideoURL":                     "https://vimeo.com/611861964",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        { 
            "ID":                           "JTJpJSgeJG",
            "displayOrder":                 "14",
            "displayDiv":                   "3",
            "rowType":                      "ConcurrentSession", 
            "HeaderId" :                    "NfOFRnUz0O",
            "ConcurrentSessionText":        "STREAM 4: Taciti sociosqu ad litora", 
            "ConcurrentSessionBGColor":     "rgba(159, 196, 251, 1)", 
            "ConcurrentSessionTextColor":   "rgba(255, 255, 255, 1)",
            "ConcurrentSessionButtonBG":    "rgba(0, 70, 176, 1)", 
            "ConcurrentSessionLastOne":     "true",
            "VideoURL":                     "https://vimeo.com/619359021",
            "inScroller":                   "true",
            "AgendaTabID":                  "ImyftecmJE"
        },
        {
            "ID":                           "k2ItothLv9",
            "displayOrder":                 "15",
            "displayDiv":                   "3",
            "rowType":                      "PlenarySession",
            "PlenarySessionHeader":         "PLENARY 3: At vero eos et accusamus et iusto odio dignissimos",
            "PlenarySessionIcon":           "/events/images/icons/plenary.png",
            "PlenarySessionInfo":           "",
            "PlenarySessionStart":          "1633834831000",
            "PlenarySessionEnd":            "1633838431000",
            "PlenarySessionTextColor":      "rgba(129, 129, 129,1)",
            "PlenarySessionBGColor":        "rgba(255, 255, 255, .8)",                                   
            "PlenarySessionButtonBGColor":  "rgba(96, 140, 96, 1)",
            "VideoURL":                     "https://vimeo.com/620172276 ",
            "inScroller":                   true,
            "AgendaTabID":                  "ImyftecmJE"
        },

        
		{
			"ID":                           "fJU1587CMf",
            "displayOrder":                 "1",
            "displayDiv":                   "3",
            "rowType":                      "PlenarySession",
			"PlenarySessionHeader":         "PLENARY 4: Accusamus et iusto odio dignissimos",
			"PlenarySessionIcon":           "/events/images/icons/plenary.png",
            "PlenarySessionInfo":           "",
            "PlenarySessionStart":          "1633901431000",
            "PlenarySessionEnd":            "1633905031000",
			"PlenarySessionTextColor":      "rgba(129, 129, 129,1)",
			"PlenarySessionBGColor":        "rgba(255, 255, 255, .5)",
			"PlenarySessionButtonBGColor":  "rgba(96, 140, 96, 1)",
            "VideoURL":                     "https://vimeo.com/216850224",
            "inScroller":                   "true",
            "AgendaTabID":                  "z8JQAOnj7Q"
		},

        { 
            "ID":                           "rezlN2XV9t",
            "displayOrder":                 "1",
            "displayDiv":                   "5",
            "rowType":                      "NextEventsList",
            "NextEventsListIcon":           "/events/images/icons/calendar.png",
            "NextEventsTextColor":          "rgba(129, 129, 129,1)",
            "NextEventsBGColor":            "rgba(255, 255, 255, .7)",
            "inScroller":                   "false"
        },
        { 
            "ID":                           "TKMQhxbyoQ",
            "displayOrder":                 "1",
            "displayDiv":                   "5",
            "rowType":                      "AddEvent",
            "AddEventListIcon":             "/events/images/icons/addEvent.png",
            "AddEventTextColor":            "rgba(129, 129, 129,1)",
            "AddEventBGColor":              "rgba(255, 255, 255, .7)",
            "AddEventButtonBG":             "rgba(96, 140, 96, 1)",
            "inScroller":                   "false"
        }
    ]
}
';
?>